"""index application registration_number and status

Revision ID: 6316316cb8b6
Revises: 8f2c4a91d6b7
Create Date: 2026-07-13 23:22:16.175037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6316316cb8b6'
down_revision: Union[str, Sequence[str], None] = '8f2c4a91d6b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_applications_registration_number'), 'applications', ['registration_number'], unique=False)
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_index(op.f('ix_applications_registration_number'), table_name='applications')
    # ### end Alembic commands ###
